export { default as IconBookOpenText } from "./IconBookOpenText.vue";
export { default as IconChevronLeft } from "./IconChevronLeft.vue";
export { default as IconChevronRight } from "./IconChevronRight.vue";
export { default as IconDial } from "./IconDial.vue";
export { default as IconGithub } from "./IconGithub.vue";
export { default as IconMagnifyingGlass } from "./IconMagnifyingGlass.vue";
export { default as IconMenu } from "./IconMenu.vue";
export { default as IconMoon } from "./IconMoon.vue";
export { default as IconRedEye } from "./IconRedEye.vue";
