
###

POST http://localhost:3001/v1/session/63ab16f85b28bf0a1031ed86
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
  "sessionToken": "-"
}

###

POST http://localhost:3001/v1/session
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
  "sessionToken": "-",
  "data": "{ \"x\": 123 }"
}

###

DELETE http://localhost:3001/v1/session/63500c4eaa6e4529e0bdcbac
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
  "sessionToken": "-"
}

###

