
###

POST http://localhost:3001/v1/session/63a5ebb719111b004d9b9b6b
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
  "sessionToken": "-"
}

###

POST http://localhost:3001/v1/session
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
  "sessionToken": "-",
  "data": "{ \"x\": 22333 }"
}

###

DELETE http://localhost:3001/v1/session/63500c4eaa6e4529e0bdcbac
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
  "sessionToken": "-"
}

###

