

###

http://localhost:3001/v1/variables
Accept: application/json
Authorization: Bearer -

###

http://localhost:3001/v1/variables/x1
Accept: application/json
Authorization: Bearer -

###

POST http://localhost:3001/v1/variables
Accept: application/json
Authorization: Bearer -
Content-Type: application/json

{
  "name": "x1",
  "value": 122
}

###

DELETE http://localhost:3001/v1/variables
Accept: application/json
Authorization: Bearer -
Content-Type: application/json

{
  "id": 21
}

###
